name: 🧠 BID Framework Enhancement
description: Suggest improvements to the Behavior Insight Design framework itself
title: "[BID Enhancement]: "
labels: ["bid-framework", "enhancement", "triage"]
assignees:
  - jrwinget
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an enhancement to the BID framework! This helps us improve the theoretical foundation and practical application of behavioral psychology in UI/UX design.
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: textarea
    id: enhancement_summary
    attributes:
      label: Enhancement Summary
      description: Brief description of the proposed BID framework enhancement
      placeholder: Summarize your enhancement in 1-2 sentences
    validations:
      required: true
  
  - type: checkboxes
    id: enhancement_type
    attributes:
      label: Enhancement Type
      description: What type of enhancement is this? (Check all that apply)
      options:
        - label: New psychological theory integration
        - label: Modification to existing BID stage
        - label: New BID stage proposal
        - label: Improved stage validation criteria
        - label: Enhanced psychological concept dictionary
        - label: Better cross-stage connections
        - label: Accessibility improvements
        - label: Cultural considerations
        - label: Other (specify in description)
  
  - type: dropdown
    id: target_stage
    attributes:
      label: Primary Target Stage
      description: Which BID stage would this enhancement primarily affect?
      options:
        - "Stage 1: Notice (Problem identification)"
        - "Stage 2: Interpret (User needs)"
        - "Stage 3: Structure (Layout design)"
        - "Stage 4: Anticipate (Behavior prediction)"
        - "Stage 5: Validate (User empowerment)"
        - "Framework architecture"
        - "All stages"
    validations:
      required: true
  
  - type: textarea
    id: current_limitation
    attributes:
      label: Current Framework Limitation
      description: What limitation in the current BID framework does this address?
      placeholder: |
        Describe the current limitation:
        
        - What aspect of behavioral psychology is missing?
        - Where does the current framework fall short?
        - What user needs are not being addressed?
    validations:
      required: true
  
  - type: textarea
    id: psychological_basis
    attributes:
      label: Psychological/Theoretical Basis
      description: What psychological theories or research support this enhancement?
      placeholder: |
        Provide the theoretical foundation:
        
        - Relevant psychological theories
        - Supporting research findings
        - Academic references
        - Real-world evidence
    validations:
      required: true
  
  - type: textarea
    id: proposed_implementation
    attributes:
      label: Proposed Implementation
      description: How would this enhancement be implemented in the bidux package?
      placeholder: |
        Describe the implementation approach:
        
        - Changes to existing functions
        - New functions or parameters
        - Updated documentation
        - Modified workflows
        
        ```r
        # Example implementation
        enhanced_function(...)
        ```
    validations:
      required: true
  
  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: What would be the impact of this enhancement?
      placeholder: |
        Assess the potential impact:
        
        **Positive impacts:**
        - Improved user experience outcomes
        - Better psychological accuracy
        - Enhanced accessibility
        
        **Potential concerns:**
        - Increased complexity
        - Breaking changes
        - Learning curve
    validations:
      required: true
  
  - type: textarea
    id: validation_criteria
    attributes:
      label: Validation Criteria
      description: How would we know if this enhancement is successful?
      placeholder: |
        Define success criteria:
        
        - Measurable outcomes
        - User feedback indicators
        - Performance metrics
        - Behavioral improvements
    validations:
      required: true
  
  - type: textarea
    id: examples
    attributes:
      label: Examples and Use Cases
      description: Provide concrete examples of how this enhancement would be used
      placeholder: |
        Provide specific examples:
        
        1. **Example 1:** [Scenario description]
        2. **Example 2:** [Scenario description]
        3. **Example 3:** [Scenario description]
    validations:
      required: true
  
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about this enhancement
      placeholder: |
        - Related research papers
        - Industry examples
        - User feedback
        - Screenshots or diagrams
    validations:
      required: false
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have provided psychological/theoretical justification
          required: true
        - label: I have considered the impact on existing users
          required: true
        - label: I have provided concrete examples and use cases
          required: true
        - label: I have defined success criteria for this enhancement
          required: true
