---
title: "introduction-to-bid"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction-to-bid}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

The Behavior Insight Design (BID) framework guides developers in integrating behavioral science into UI/UX design. It helps in understanding psychological principles and biases that affect user interactions.

The five stages of the BID framework are:
1. **Interpret the User's Need**: Clarify the core question and build a data narrative.
2. **Notice the Problem**: Identify friction points and areas of high cognitive load.
3. **Anticipate User Behavior**: Mitigate biases such as anchoring and framing.
4. **Structure the Dashboard**: Organize layout and design to enhance usability.
5. **Validate & Empower the User**: Summarize insights and facilitate collaborative decision-making.

This vignette introduces the core ideas behind each stage and how they interact to create effective, bias-aware dashboards.

Visit [github.com/jrwinget/bid-framework](https://github.com/jrwinget/bid-framework) for resources and further information on the BID framework.
