name: Bug Report
description: Report a bug in the {bidux} package
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - jrwinget
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! This helps us improve the {bidux} package for everyone.
        
        **Before submitting:** Please search existing issues to see if this bug has already been reported.
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true
  
  - type: dropdown
    id: bid_stage
    attributes:
      label: BID Framework Stage
      description: Which stage of the BID framework does this bug affect?
      options:
        - "Stage 1: Notice"
        - "Stage 2: Interpret"
        - "Stage 3: Structure"
        - "Stage 4: Anticipate"
        - "Stage 5: Validate"
        - "Cross-stage functionality"
        - "Package utilities"
        - "Documentation/Vignettes"
        - "Not applicable"
    validations:
      required: true
  
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Provide a minimal reproducible example
      placeholder: |
        ```r
        library(bidux)
        
        # Your code here that reproduces the bug
        ```
    validations:
      required: true
  
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior
    validations:
      required: true
  
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages
      placeholder: |
        Describe the actual behavior and include any error messages:
        
        ```
        Error: [paste error message here]
        ```
    validations:
      required: true
  
  - type: textarea
    id: session_info
    attributes:
      label: Session Information
      description: Run `sessionInfo()` in R and paste the output here
      placeholder: |
        ```r
        sessionInfo()
        ```
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - "Critical - Package is unusable"
        - "High - Core functionality broken"
        - "Medium - Some functionality affected"
        - "Low - Minor issue or inconvenience"
    validations:
      required: true
  
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: Please check all that apply
      options:
        - label: RStudio Desktop
        - label: RStudio Server
        - label: VSCode with R extension
        - label: R Console
        - label: Jupyter Notebook
        - label: Other (specify in additional context)
  
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots (if applicable)
        - Related issues or PRs
        - Any other relevant information
    validations:
      required: false
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for this bug
          required: true
        - label: I have provided a minimal reproducible example
          required: true
        - label: I have included my session information
          required: true
        - label: I have checked the documentation and vignettes
          required: true
