blank_issues_enabled: false
contact_links:
  - name: 📚 Package Documentation
    url: https://jrwinget.github.io/bidux/
    about: Browse the complete package documentation and vignettes
  - name: 🧠 BID Framework Resources
    url: https://github.com/jrwinget/bid-framework
    about: Learn more about the Behavioral Insight Design framework
